version: '3.7'

services: 
  client:
    image: tarea1_client:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8081:8080
    environment:
      - REST_URL=http://18.116.44.28:8000/image_server/pixels/
    volumes:
      - ./image/:/usr/src/app/image