version: '3.7'

services: 
  client:
    image: tarea1_client:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports: 
      - 8081:8080
    volumes:
      - ./image/:/usr/src/app/image